//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.13 at 11:28:01 PM MSK 
//


package ru.mirea.orgserver.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.mirea.orgserver.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.mirea.orgserver.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Organization.Leaders }
     * 
     */
    public Organization.Leaders createOrganizationLeaders() {
        return new Organization.Leaders();
    }

    /**
     * Create an instance of {@link Organization.Leaders.Leader }
     * 
     */
    public Organization.Leaders.Leader createOrganizationLeadersLeader() {
        return new Organization.Leaders.Leader();
    }

    /**
     * Create an instance of {@link Organization.Founders }
     * 
     */
    public Organization.Founders createOrganizationFounders() {
        return new Organization.Founders();
    }

    /**
     * Create an instance of {@link Organization.Founders.Founder }
     * 
     */
    public Organization.Founders.Founder createOrganizationFoundersFounder() {
        return new Organization.Founders.Founder();
    }

    /**
     * Create an instance of {@link Organization.Okveds }
     * 
     */
    public Organization.Okveds createOrganizationOkveds() {
        return new Organization.Okveds();
    }

    /**
     * Create an instance of {@link GetOrganizationByOgrnResponse }
     * 
     */
    public GetOrganizationByOgrnResponse createGetOrganizationByOgrnResponse() {
        return new GetOrganizationByOgrnResponse();
    }

    /**
     * Create an instance of {@link GetOrganizationByOgrnRequest }
     * 
     */
    public GetOrganizationByOgrnRequest createGetOrganizationByOgrnRequest() {
        return new GetOrganizationByOgrnRequest();
    }

    /**
     * Create an instance of {@link Organization.Name }
     * 
     */
    public Organization.Name createOrganizationName() {
        return new Organization.Name();
    }

    /**
     * Create an instance of {@link Organization.Leaders.Leader.Name }
     * 
     */
    public Organization.Leaders.Leader.Name createOrganizationLeadersLeaderName() {
        return new Organization.Leaders.Leader.Name();
    }

    /**
     * Create an instance of {@link Organization.Founders.Founder.Name }
     * 
     */
    public Organization.Founders.Founder.Name createOrganizationFoundersFounderName() {
        return new Organization.Founders.Founder.Name();
    }

    /**
     * Create an instance of {@link Organization.Founders.Founder.Capital }
     * 
     */
    public Organization.Founders.Founder.Capital createOrganizationFoundersFounderCapital() {
        return new Organization.Founders.Founder.Capital();
    }

    /**
     * Create an instance of {@link Organization.Okveds.Okved }
     * 
     */
    public Organization.Okveds.Okved createOrganizationOkvedsOkved() {
        return new Organization.Okveds.Okved();
    }

}
