//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 03:15:15 PM MSK 
//


package ru.mirea.orgserver.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
 *         &lt;element name="okveds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="okved" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="main" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="founders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="founder" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
 *                             &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="capital">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="percent" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="leaders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="leader" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
 *                             &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="position_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="inn" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="kpp" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organization", propOrder = {
    "name",
    "okveds",
    "founders",
    "leaders",
    "status"
})
public class Organization {

    @XmlElement(required = true)
    protected Name name;
    @XmlElement(required = true)
    protected Organization.Okveds okveds;
    @XmlElement(required = true)
    protected Organization.Founders founders;
    @XmlElement(required = true)
    protected Organization.Leaders leaders;
    @XmlElement(required = true)
    protected String status;
    @XmlAttribute(name = "ogrn")
    protected Long ogrn;
    @XmlAttribute(name = "inn")
    protected Long inn;
    @XmlAttribute(name = "kpp")
    protected Long kpp;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the okveds property.
     * 
     * @return
     *     possible object is
     *     {@link Organization.Okveds }
     *     
     */
    public Organization.Okveds getOkveds() {
        return okveds;
    }

    /**
     * Sets the value of the okveds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization.Okveds }
     *     
     */
    public void setOkveds(Organization.Okveds value) {
        this.okveds = value;
    }

    /**
     * Gets the value of the founders property.
     * 
     * @return
     *     possible object is
     *     {@link Organization.Founders }
     *     
     */
    public Organization.Founders getFounders() {
        return founders;
    }

    /**
     * Sets the value of the founders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization.Founders }
     *     
     */
    public void setFounders(Organization.Founders value) {
        this.founders = value;
    }

    /**
     * Gets the value of the leaders property.
     * 
     * @return
     *     possible object is
     *     {@link Organization.Leaders }
     *     
     */
    public Organization.Leaders getLeaders() {
        return leaders;
    }

    /**
     * Sets the value of the leaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization.Leaders }
     *     
     */
    public void setLeaders(Organization.Leaders value) {
        this.leaders = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the ogrn property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOgrn() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOgrn(Long value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInn(Long value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKpp() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKpp(Long value) {
        this.kpp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="founder" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
     *                   &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="capital">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="percent" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "founder"
    })
    public static class Founders {

        @XmlElement(required = true)
        protected List<Organization.Founders.Founder> founder;

        /**
         * Gets the value of the founder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the founder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFounder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Organization.Founders.Founder }
         * 
         * 
         */
        public List<Organization.Founders.Founder> getFounder() {
            if (founder == null) {
                founder = new ArrayList<Organization.Founders.Founder>();
            }
            return this.founder;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
         *         &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="capital">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="percent" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "entityType",
            "capital"
        })
        public static class Founder {

            @XmlElement(required = true)
            protected Name name;
            @XmlElement(name = "entity_type", required = true)
            protected String entityType;
            @XmlElement(required = true)
            protected Organization.Founders.Founder.Capital capital;
            @XmlAttribute(name = "ogrn")
            protected Long ogrn;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link Name }
             *     
             */
            public Name getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link Name }
             *     
             */
            public void setName(Name value) {
                this.name = value;
            }

            /**
             * Gets the value of the entityType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntityType() {
                return entityType;
            }

            /**
             * Sets the value of the entityType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntityType(String value) {
                this.entityType = value;
            }

            /**
             * Gets the value of the capital property.
             * 
             * @return
             *     possible object is
             *     {@link Organization.Founders.Founder.Capital }
             *     
             */
            public Organization.Founders.Founder.Capital getCapital() {
                return capital;
            }

            /**
             * Sets the value of the capital property.
             * 
             * @param value
             *     allowed object is
             *     {@link Organization.Founders.Founder.Capital }
             *     
             */
            public void setCapital(Organization.Founders.Founder.Capital value) {
                this.capital = value;
            }

            /**
             * Gets the value of the ogrn property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getOgrn() {
                return ogrn;
            }

            /**
             * Sets the value of the ogrn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setOgrn(Long value) {
                this.ogrn = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="percent" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "size",
                "percent"
            })
            public static class Capital {

                protected long size;
                protected double percent;

                /**
                 * Gets the value of the size property.
                 * 
                 */
                public long getSize() {
                    return size;
                }

                /**
                 * Sets the value of the size property.
                 * 
                 */
                public void setSize(long value) {
                    this.size = value;
                }

                /**
                 * Gets the value of the percent property.
                 * 
                 */
                public double getPercent() {
                    return percent;
                }

                /**
                 * Sets the value of the percent property.
                 * 
                 */
                public void setPercent(double value) {
                    this.percent = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="leader" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
     *                   &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="position_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leader"
    })
    public static class Leaders {

        @XmlElement(required = true)
        protected List<Organization.Leaders.Leader> leader;

        /**
         * Gets the value of the leader property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the leader property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLeader().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Organization.Leaders.Leader }
         * 
         * 
         */
        public List<Organization.Leaders.Leader> getLeader() {
            if (leader == null) {
                leader = new ArrayList<Organization.Leaders.Leader>();
            }
            return this.leader;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.mirea.ru/orgserver/model}name"/>
         *         &lt;element name="entity_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="position_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ogrn" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "entityType",
            "positionName"
        })
        public static class Leader {

            @XmlElement(required = true)
            protected Name name;
            @XmlElement(name = "entity_type", required = true)
            protected String entityType;
            @XmlElement(name = "position_name", required = true)
            protected String positionName;
            @XmlAttribute(name = "ogrn")
            protected Long ogrn;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link Name }
             *     
             */
            public Name getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link Name }
             *     
             */
            public void setName(Name value) {
                this.name = value;
            }

            /**
             * Gets the value of the entityType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntityType() {
                return entityType;
            }

            /**
             * Sets the value of the entityType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntityType(String value) {
                this.entityType = value;
            }

            /**
             * Gets the value of the positionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPositionName() {
                return positionName;
            }

            /**
             * Sets the value of the positionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPositionName(String value) {
                this.positionName = value;
            }

            /**
             * Gets the value of the ogrn property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getOgrn() {
                return ogrn;
            }

            /**
             * Sets the value of the ogrn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setOgrn(Long value) {
                this.ogrn = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="okved" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="main" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "okved"
    })
    public static class Okveds {

        @XmlElement(required = true)
        protected List<Organization.Okveds.Okved> okved;

        /**
         * Gets the value of the okved property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the okved property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOkved().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Organization.Okveds.Okved }
         * 
         * 
         */
        public List<Organization.Okveds.Okved> getOkved() {
            if (okved == null) {
                okved = new ArrayList<Organization.Okveds.Okved>();
            }
            return this.okved;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="main" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "name"
        })
        public static class Okved {

            @XmlElement(required = true)
            protected String code;
            @XmlElement(required = true)
            protected String name;
            @XmlAttribute(name = "version")
            protected Long version;
            @XmlAttribute(name = "main")
            protected String main;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setVersion(Long value) {
                this.version = value;
            }

            /**
             * Gets the value of the main property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMain() {
                return main;
            }

            /**
             * Sets the value of the main property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMain(String value) {
                this.main = value;
            }

        }

    }

}
