//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.15 at 10:38:43 PM MSK 
//


package ru.mirea.pizza.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.mirea.pizza package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.mirea.pizza
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterUserRequest }
     * 
     */
    public RegisterUserRequest createRegisterUserRequest() {
        return new RegisterUserRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ShowIngridientsResponse }
     * 
     */
    public ShowIngridientsResponse createShowIngridientsResponse() {
        return new ShowIngridientsResponse();
    }

    /**
     * Create an instance of {@link Topping }
     * 
     */
    public Topping createTopping() {
        return new Topping();
    }

    /**
     * Create an instance of {@link MakePizzaResponse }
     * 
     */
    public MakePizzaResponse createMakePizzaResponse() {
        return new MakePizzaResponse();
    }

    /**
     * Create an instance of {@link MakeOrderResponse }
     * 
     */
    public MakeOrderResponse createMakeOrderResponse() {
        return new MakeOrderResponse();
    }

    /**
     * Create an instance of {@link ShowOrderResponse }
     * 
     */
    public ShowOrderResponse createShowOrderResponse() {
        return new ShowOrderResponse();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link ShowPizzaResponse }
     * 
     */
    public ShowPizzaResponse createShowPizzaResponse() {
        return new ShowPizzaResponse();
    }

    /**
     * Create an instance of {@link Pizza }
     * 
     */
    public Pizza createPizza() {
        return new Pizza();
    }

    /**
     * Create an instance of {@link MakeOrderRequest }
     * 
     */
    public MakeOrderRequest createMakeOrderRequest() {
        return new MakeOrderRequest();
    }

    /**
     * Create an instance of {@link ShowPizzaRequest }
     * 
     */
    public ShowPizzaRequest createShowPizzaRequest() {
        return new ShowPizzaRequest();
    }

    /**
     * Create an instance of {@link ShowIngridientsRequest }
     * 
     */
    public ShowIngridientsRequest createShowIngridientsRequest() {
        return new ShowIngridientsRequest();
    }

    /**
     * Create an instance of {@link ShowOrderRequest }
     * 
     */
    public ShowOrderRequest createShowOrderRequest() {
        return new ShowOrderRequest();
    }

    /**
     * Create an instance of {@link RegisterUserResponse }
     * 
     */
    public RegisterUserResponse createRegisterUserResponse() {
        return new RegisterUserResponse();
    }

    /**
     * Create an instance of {@link MakePizzaRequest }
     * 
     */
    public MakePizzaRequest createMakePizzaRequest() {
        return new MakePizzaRequest();
    }

}
